### ISSUE TITLE
ArsTechnica links include a menu and a footer

### ISSUE THREAD

**Issue by matejdro** [bunglegrind/save-as-ebook#22]
A minor issue: When attempting to save ars technica article, for example

https://arstechnica.com/space/2023/11/heres-why-this-weekends-starship-launch-was-actually-a-huge-success/

resulting epub includes a menu at the top:

![image](https://github.com/bunglegrind/save-as-ebook/assets/507922/7ea3aaa3-cd5c-40e3-9779-b04f6a0f1746)

and a footer at the bottom:

![image](https://github.com/bunglegrind/save-as-ebook/assets/507922/3e6bbb02-b99e-481f-b156-6a39fd31d639)

Both of these are not there in Firefox's reader mode.

**Comment by bunglegrind** [comment]
Well, let me explain my typical use case, which acts as the foundation of my fork:
basically, when I'm converting a page, I wrote a custom css rule to get rid of all of the content I don't need (usually sidebars, menus, ads, annoying popups, accessibility menus like the one you indicated, etc.). and to stretch the main content to the 100% of the page. Firefox Style Editor and an ublock origin are the tools I employ. 

For instance:

```json
        {
            "style": "#navigation,\n#banner,\n#footer,\n.navigate,\n#commentform,\n.entry-footer\n{\n  display: none;\n  \n}\ndiv#content\n{\n  max-width: 100%;!important;\n  margin: 0!important;\n}\n\n.wp-block-image img\n{\n    max-width: 35em!important;\n}\n\nfigure {\n    margin: 0!important;\n}",
            "title": "Chip Morningstar",
            "url": "habitatchronicles\\.com"
        }
```

This is part of the json file my fork is able to import/export.

That said, to answer your question, it's out of scope selecting which page component must go into the epub, because, well, it's subjective. 
However, there's an open issue about this #8 but probably, just using the advanced tools ublock origin already exposes it's enough.

**Comment by matejdro** [comment]
Thanks for the answer, closing in favor of #8.
